version: "3.0"

expectations:
  population_size: 1000

actions:
  generate_dataset:
    run: >
      ehrql:latest
        generate-dataset
        --output output/dataset.csv
        analysis/dataset_definition.py
    outputs:
      highly_sensitive:
        dataset: output/dataset.csv

  count_by_age:
    run: >
      r:v2
        Rscript analysis/eda.R
    needs: [generate_dataset]
    outputs:
      moderately_sensitive:
        plots: output/*.png
        data: output/*.csv
# Isolation disabled due to not supporting on mac?